module Sound.Tidal.MIDI.Kindohm.CustomParams where

import Sound.Tidal.Params

(noise, noise_p) = pF "noise" (Just 0)
(shape1, shape1_p) = pF "shape1" (Just 0)
(shape2, shape2_p) = pF "shape2" (Just 0)
(vol1, vol1_p) = pF "vol1" (Just 1)
(vol2, vol2_p) = pF "vol2" (Just 1)
(xmod, xmod_p) = pF "xmod" (Just 0)
(pitchmod, pitchmod_p) = pF "pitchmod" (Just 0.5)
(egint, egint_p) = pF "egint" (Just 0.5)
(egattack, egattack_p) = pF "egattack" (Just 0)
(egdecay, egdecay_p) = pF "egdecay" (Just 0)
(egsustain, egsustain_p) = pF "egsustain" (Just 1)
(egrelease, egrelease_p) = pF "egrelease" (Just 0)
(voicedepth, voicedepth_p) = pF "voicedepth" (Just 0)
(oct1, oct1_p) = pF "oct1" (Just 0.5)
(oct2, oct2_p) = pF "oct2" (Just 0.5)
(wave1, wave1_p) = pF "wave1" (Just 1)
(wave2, wave2_p) = pF "wave2" (Just 1)
(sync, sync_p) = pF "sync" (Just 0)
(ring, ring_p) = pF "ring" (Just 0)
(lfotarget, lfotarget_p) = pF "lfotarget" (Just 0)
(lforate, lforate_p) = pF "lforate" (Just 0)
(lfomod, lfomod_p) = pF "lfomod" (Just 0)
(lfowave, lfowave_p) = pF "lfowave" (Just 0.5)
